### ISSUE TITLE
failing on first run

### ISSUE THREAD

**Issue by datkidpatrick** [taux1c/onlyfans-scraper#19]
install command works fine.. when i go to run it with "onlyfans-scraper" i get this error, im not sure if i messed something up along the way
![Screenshot 2022-09-10 000744](https://user-images.githubusercontent.com/88197675/189468066-372ad726-17dc-4658-bafe-dc008ecd0c54.png)

**Comment by taux1c** [comment]
This should be fixed, I added some prep for the ability to change file locations naming. Committed those changes by mistake.

**Comment by taux1c** [comment]
You will need to `pip uninstall onlyfans-scraper` and then run the install command again.

**Comment by datkidpatrick** [comment]
thank you! worked like a charm...
