### ISSUE TITLE
Getting Errno 11001

### ISSUE THREAD

**Issue by fckthsshtcool** [taux1c/onlyfans-scraper#24]
OS:  Windows 10

Traceback: [Errno 11001] getaddrinfo failed

Python Version: 3.10

After downloading for a bit, this error pops up repeatedly, and the download "completes" without downloading everything. Is there any particular fix to this? 

Below is an example of what I'm seeing towards the end before the program quits.

`[Errno 11001] getaddrinfo failed
[Errno 11001] getaddrinfo failed
[Errno 11001] getaddrinfo failed
[Errno 11001] getaddrinfo failed
[Errno 11001] getaddrinfo failed
[Errno 11001] getaddrinfo failed
[Errno 11001] getaddrinfo failed
[Errno 11001] getaddrinfo failed
[Errno 11001] getaddrinfo failed
[Errno 11001] getaddrinfo failed
[Errno 11001] getaddrinfo failed
[Errno 11001] getaddrinfo failed
[Errno 11001] getaddrinfo failed
[Errno 11001] getaddrinfo failed
[Errno 11001] getaddrinfo failed
[Errno 11001] getaddrinfo failed
[Errno 11001] getaddrinfo failed
[Errno 11001] getaddrinfo failed
[Errno 11001] getaddrinfo failed
[Errno 11001] getaddrinfo failed
Progress: (31 photos, 22 videos, 0 skipped || 9.56 GB): 100%|████████████████████████| 351/351 [05:35<00:00,  1.05it/s]`

(Notice that the number downloaded does not match number scraped)

**Comment by taux1c** [comment]
This means there is no connection to the internet. Basically, it sounds like your connection is flooded by all the connections trying to download the files for you and thus some time out (reason for not downloading) and others become unreachable (connection already full).

This can be reduced by editing the download.py file, line 49.  I am looking at moving it to a ~/.config/onlyfans-scraper/config.json but it isn't there yet. Unfortunately you would need to find the install directory (python programs) root on your system or for your account (more likely) and edit the download.py file there. 

[Here is a link so you can look at it. ](https://github.com/taux1c/onlyfans-scraper/blob/7d745cbc08e4e18143b5ef73ba58765247f39792/onlyfans_scraper/utils/download.py#L49)

An easier way would be just search your system for download.py (if on windows) and (locate on linux) and then open the file with notepad and find said line. Just reduce the number of max connections and make keep alive connections until you stop getting the error. (You may need to  drop them both to 1. Obviously you can't go below 1 or it wont work.)  If it still does this try using ping while it's happening to see if ping fails also. 

Ultimately it's a python error stating that python can't connect to the internet and thus can't feed the connection to the scraper program. If you are supposed to have a strong connection you may want to try troubleshooting your connection and maybe using something like [ping plotter](https://www.pingplotter.com/).
