### ISSUE TITLE
Request: resolve import issues for newbie programmers in vscode (ImportError from .api import init)

### ISSUE THREAD

**Issue by LuminairPrime** [taux1c/onlyfans-scraper#36]
I know that dealing with different development environments and importing from relative paths on different machines can be a hassle on any project. I just cloned onlyfans-scraper into vscode and got this trying to run it:

> from .api import init, highlights, me, messages, posts, profile, subscriptions
> ImportError: attempted relative import with no known parent package

There's definitely an obvious explanation that you could tell me, but I'm wondering if we can write it down for the next guy who comes along :D

**Comment by taux1c** [comment]
Can you post the stack? It should have details about which module is encountering the error.

**Comment by taux1c** [comment]
I don't plan to make any real changes to the program aside from small patches to keep it working until the v3 api is released at which point it will likely be retired. Just seems like a waste of time. If you want you can make the changes and create a PR.
