### ISSUE TITLE
404 error when trying to load your BuyMeACoffee.com page

### ISSUE THREAD

**Issue by AwkwardCauliflower** [taux1c/onlyfans-scraper#49]
**Describe the bug**

https://www.buymeacoffee.com/taux1c returns a 404 error page.

**Comment by TheOne4TheRest** [comment]
That is fine. Scraper works just the same. That was just a page for something that didn’t involve the functionality of the scraper.

**Comment by taux1c** [comment]
Also, side note I no longer maintain the repo or really even sign into github.
