### ISSUE TITLE
auth failed

### ISSUE THREAD

**Issue by Zewaria** [taux1c/onlyfans-scraper#57]
my ofscraper tries to login 10 attempts with no success and ends in "auth failed".. why is that and how to fix it?

**Comment by Klessc** [comment]
Checked my auth file with what is present on my system and it also states that the Status is Down for me, getting a 400 Bad Request, even though everything is correct. even attempted with diffrent auth from separate pc and still no go.

**Comment by le0nr** [comment]
how can we fix it?

**Comment by Zewaria** [comment]
how to fix??

**Comment by WhyComaWhite** [comment]
Can anything be done to this script to make it work?

**Comment by gman773** [comment]
Change row 48 in constants.py
From DC_EP = 'https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json'
To DC_EP = 'https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json'

Reference 
https://github.com/DATAHOARDERS/dynamic-rules

**Comment by le0nr** [comment]
OnlyFans is down now

**Comment by gman773** [comment]
> It gives me Status: Down, even if I double checked api credentials

OF seem to be experiencing technical difficulties at the current time. It worked for me when I did the update yesterday.

**Comment by WhyComaWhite** [comment]
> Change row 48 in constants.py From DC_EP = 'https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json' To DC_EP = 'https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json'
> 
> Reference https://github.com/DATAHOARDERS/dynamic-rules

Thanks a lot. The new file is too fast, is there any way to fix this?

**Comment by le0nr** [comment]
it's working now guys

**Comment by Boomeroo** [comment]
Hi there.. Any chance to keep the Like Option alive? Any help would be super appreciated. Thanks so much in advance

**Comment by shurialvaro** [comment]
> Change row 48 in constants.py From DC_EP = 'https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json' To DC_EP = 'https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json'
> 
> Reference https://github.com/DATAHOARDERS/dynamic-rules

Doesnt Work on my end sadly

**Comment by ablamj** [comment]
> > Change row 48 in constants.py From DC_EP = 'https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json' To DC_EP = 'https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json'
> > Reference https://github.com/DATAHOARDERS/dynamic-rules
> 
> Doesnt Work on my end sadly

not for me either :(

**Comment by aporzio1** [comment]
works for me as far as authenticating but I get an error, it looks like its for every file 

`Illegal header value b'\nMozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'`

**Comment by Boomeroo** [comment]
> works for me as far as authenticating but I get an error, it looks like its for every file
> 
> `Illegal header value b'\nMozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'`

nMozilla?

**Comment by vajdao** [comment]
> Change row 48 in constants.py From DC_EP = 'https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json' To DC_EP = 'https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json'
> 
> Reference https://github.com/DATAHOARDERS/dynamic-rules

works like a dream, thanks bro! :)

**Comment by thisisme79** [comment]
> Change row 48 in constants.py From DC_EP = 'https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json' To DC_EP = 'https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json'
> 
> Reference https://github.com/DATAHOARDERS/dynamic-rules

Doesn't work for me either, still listed as down :-/

**Comment by vajdao** [comment]
> > Change row 48 in constants.py From DC_EP = 'https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json' To DC_EP = 'https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json'
> > Reference https://github.com/DATAHOARDERS/dynamic-rules
> 
> Doesn't work for me either, still listed as down :-/

Make sure to edit the source file under:
%localappdata%\Programs\Python\Python311\Lib\site-packages\onlyfans_scraper\
(in case if you have Python 3.11)
If you got any other, then just go until this folder: %localappdata%\Programs\Python\ and then manually enter the directories until you reach the **constants.py** under the main directory in onlyfans_scraper

Side note, it does not specifically has to be in the row 48, for example in my case I've found it at row 43. Easiest is to just simply CTRL+F the DC_EP

**Comment by thisisme79** [comment]
> > > Change row 48 in constants.py From DC_EP = 'https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json' To DC_EP = 'https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json'
> > > Reference https://github.com/DATAHOARDERS/dynamic-rules
> > 
> > 
> > Doesn't work for me either, still listed as down :-/
> 
> Make sure to edit the source file under: %localappdata%\Programs\Python\Python311\Lib\site-packages\onlyfans_scraper (in case if you have Python 3.11) If you got any other, then just go until this folder: %localappdata%\Programs\Python\ and then manually enter the directories until you reach the **constants.py** under the main directory in onlyfans_scraper
> 
> Side note, it does not specifically has to be in the row 48, for example in my case I've found it at row 43. Easiest is to just simply CTRL+F the DC_EP

Correction, I am an idiot who can't read, and doesn't know how to spell...  Now shows as up for me as well...

**Comment by Boomeroo** [comment]
Changed it but It's still down.. Just wondering if anybody else is still strugglin with this

**Comment by dvkrav** [comment]
Does'nt work for me. Status still is DOWN

**Comment by evthar** [comment]
> Change row 48 in constants.py From DC_EP = 'https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json' To DC_EP = 'https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json'
> 
> Reference https://github.com/DATAHOARDERS/dynamic-rules

This is working for me today, though the line number that needs updating is different. 

So if you're still having issues, rather than just editing line 48 of that file, find the line starting DC_EP and make the change.

It was also compounded by a browser update, requiring the normal auth.json update to match the cookie and user agent strings.

**Comment by vajdao** [comment]
> > Change row 48 in constants.py From DC_EP = 'https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json' To DC_EP = 'https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json'
> > Reference https://github.com/DATAHOARDERS/dynamic-rules
> 
> This is working for me today, though the line number that needs updating is different.
> 
> So if you're still having issues, rather than just editing line 48 of that file, find the line starting DC_EP and make the change.
> 
> It was also compounded by a browser update, requiring the normal auth.json update to match the cookie and user agent strings.

Yepp this is what I mentioned 2days ago at https://github.com/taux1c/onlyfans-scraper/issues/57#issuecomment-1627785861

**Comment by MikeBarberry** [comment]
This worked for me today. Saw same posted before and just tried it.

**Comment by dvkrav** [comment]
i installed on mac using pip install. where is the location of this file which i need to modify ?

**Comment by MikeBarberry** [comment]
you can run "find ./ -name constants.py" from $HOME in your terminal and it
will output the absolute paths of all files with the name constants.py.

For me, the onlyfans-scraper one is located at
./.local/lib/python3.10/site-packages/onlyfans_scraper/constants.py

**Comment by RedDeadRandy** [comment]
no need. just do 
`pip show onlyfans-scraper`

> you can run "find ./ -name constants.py | grep onlyfans_scraper" from your terminal and it will output the relative path. try it from ~ first and then /. You can get to ~ and / by running "cd ~" or "cd /" before the first command.

**Comment by tdex89** [comment]
Modify the line ans it still behaves the same way. Also tried to uninstall and reinstall with the same results. Is there another fhile that needs to be modified as well?

**Comment by dvkrav** [comment]
thks above comments helped

**Comment by jamesle3199** [comment]
> Change row 48 in constants.py From DC_EP = 'https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json' To DC_EP = 'https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json'
> 
> Reference https://github.com/DATAHOARDERS/dynamic-rules

i love you

**Comment by taux1c** [comment]
This repo is outdated (no longer works) and I am no longer maintaining it.
