### ISSUE TITLE
'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by Xenonfish** [taux1c/onlyfans-scraper#81]
Hi taux1c,

I know you're not maintaining this anymore but just wondered if you could provide any insight on an issue I'm getting when trying to download content from a specific user. I have been using the scraper for some time and have not encountered this before, I see some other people have also previously asked about it.

It downloaded some pictures from the user but no videos and gave the error:   'NoneType' object has no attribute 'split'.

I tried with a different user and didn't get the same error and it downloaded without issue. 

I read in one of the other threads that it was DRM related and that the content needing decrypting, so by this I assume it is because some users on OF have the option to protect their content, by streaming it in chunks? 

If I encounter this error for a specific user then does that mean I am unable to scrape their video content at all (with the current API?)

I'd be grateful for your feedback.

**Comment by taux1c** [comment]
This is their new DMCA attempt. They have changed the way videos work (based on my understanding from the community.). I actually don't have any subscriptions anymore so I can't say for sure. I am flirting with the idea of creating a new software (or updating this one). 

If you are interested in someone doing it for you check here:

https://discord.gg/jwdwYjYN4k
